# Generated by Django 4.2 on 2024-03-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mfy", "0002_villageinventor"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeeker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "home_number",
                    models.CharField(max_length=256, verbose_name="Home number"),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Address"),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Full name"
                    ),
                ),
                (
                    "specialist",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Specialist"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Phone number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Seeker",
                "verbose_name_plural": "Job Seekers",
            },
        ),
        migrations.CreateModel(
            name="VillageBusinnesmen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        max_length=512, null=True, verbose_name="Legal name"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "certificate_photo",
                    models.ImageField(
                        upload_to="certificate_photo", verbose_name="Certificate photo"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=512, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Village Businnesmen",
                "verbose_name_plural": "Village Businnesmens",
            },
        ),
        migrations.CreateModel(
            name="VillageBusinnesmenProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "name",
                    models.CharField(max_length=512, null=True, verbose_name="Name"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_photo",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="Price"
                    ),
                ),
            ],
            options={
                "verbose_name": "Village Businnesmen Product",
                "verbose_name_plural": "Village Businnesmen Products",
            },
        ),
    ]
