name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  SSH_HOST: ${{ secrets.SERVER_IP }}
  SSH_USER: ${{ secrets.SERVER_USERNAME }}
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          sudo mkdir -p /var/www/backends/zilol_mfy
          cd /var/www/backends/zilol_mfy || exit
          # sudo https://github.com/abduraximov/zilol_mfy.git .
          # docker-compose -f prod.yml up -d --build
