on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      run: |
          whoami
          cd /var/www/zilol_mfy
          git pull
          docker compose -f prod.yml up -d --build
