on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run_pull:
    name: run pull
    runs-on: self-hosted
    steps:
    - name: connect and pull
      working-directory: /var/www/zilol_mfy
      run: |
          whoami
          cd /var/www/zilol_mfy
          git pull
          sudo docker compose -f prod.yml up -d --build
