name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy
        run: |
          cd /var/www/zilol_mfy || exit
          sudo git clone https://github.com/yourusername/yourproject.git .
          docker-compose -f prod.yml up -d --build
